# Generated by Django 4.2.6 on 2024-04-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eight", "0003_borrowedbook"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="borrowedbook",
            name="user",
        ),
        migrations.AddField(
            model_name="borrowedbook",
            name="client_name",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
