# Generated by Django 4.2.6 on 2024-04-05 12:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("eight", "0005_borrowedbook_book_copies"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="name",
            new_name="Title",
        ),
        migrations.AddField(
            model_name="borrowedbook",
            name="fine_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="borrowedbook",
            name="borrow_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
