# Generated by Django 4.2.6 on 2024-04-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eight", "0007_rename_availablility_book_availability"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowedbook",
            name="book_copies",
            field=models.IntegerField(default=0),
        ),
    ]
